# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gulp Starter Kit
description: A simple starter kit using Gulp to get a local website up and running
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown

lib: assets
img: assets/images
ico: assets/images/favicons
scss: assets/scss
css: assets/css
js: assets/js

# Exclude metadata and development time dependencies
exclude: ["README.md", "package.json", "gulpfile.js", "node_modules", ".asset-cache", ".jekyll-metadata"]
